### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by FarSeenNomic** [nikolaischunk/discord-phishing-links#484]
The URL "discord.app" redirects to the official discord.
In the upcoming days I want to make a quick script to check which of these have been legitimized over the years this useful project has been running.

**Comment by nikolaischunk** [comment]
Hi, thanks for your interest in this work.
Just because a domain now redirects to discord, is not reason enough to remove it from the list, since this redirect can easily be changed to something else at a later time.

Since discord is not owning this domain directly, and is obviously trying to impersonate discord, we will keep this domain on the list.

See also this[ reddit thread](https://www.reddit.com/r/discordapp/comments/13snsc8/doesnt_discord_own_the_discordapp_domain_it/) for reference.
